[h100-24h]
queue = "gpuh100"
wall_time = "24:00"
cores = 17
memory = "4GB"
gpu = "num=1:mode=exclusive_process"
email = "s234805@dtu.dk"
job_name_prefix = "codllm"
storage_folder = "/work3/$USER"
modules = ["cuda/12.2"]

[h100-10h]
queue = "gpuh100"
wall_time = "10:00"
cores = 17
memory = "4GB"
gpu = "num=1:mode=exclusive_process"
email = "s234805@dtu.dk"
job_name_prefix = "codllm"
storage_folder = "/work3/$USER"
modules = ["cuda/12.2"]

[h100-5h]
queue = "gpuh100"
wall_time = "5:00"
cores = 17
memory = "4GB"
gpu = "num=1:mode=exclusive_process"
email = "s234805@dtu.dk"
job_name_prefix = "codllm"
storage_folder = "/work3/$USER"
modules = ["cuda/12.2"]

[h100-4h]
queue = "gpuh100"
wall_time = "4:00"
cores = 17
memory = "4GB"
gpu = "num=1:mode=exclusive_process"
email = "s234805@dtu.dk"
job_name_prefix = "codllm"
storage_folder = "/work3/$USER"
modules = ["cuda/12.2"]

[h100-3h]
queue = "gpuh100"
wall_time = "3:00"
cores = 17
memory = "4GB"
gpu = "num=1:mode=exclusive_process"
email = "s234805@dtu.dk"
job_name_prefix = "codllm"
storage_folder = "/work3/$USER"
modules = ["cuda/12.2"]

[h100-2h]
queue = "gpuh100"
wall_time = "2:00"
cores = 17
memory = "4GB"
gpu = "num=1:mode=exclusive_process"
email = "s234805@dtu.dk"
job_name_prefix = "codllm"
storage_folder = "/work3/$USER"
modules = ["cuda/12.2"]

[v100]
queue = "gpuv100"
wall_time = "10:00"
cores = 4
memory = "6GB"
gpu = "num=1:mode=exclusive_process"
email = "s234805@dtu.dk"
job_name_prefix = "codllm"
storage_folder = "/work3/$USER"
modules = ["cuda/12.2"]
extra_resources = ["select[gpu32gb]"]
