base = "../base/h100-large.toml"
name = "multicod"
description = "Sweep to test multicod synthetic data effectiveness"
force_reprocess = false

[env]
CODLLM_LR = 2.5e-5
CODLLM_NUM_TRAIN_EPOCHS = 8
CODLLM_MAX_LABEL_COUNT = 3
CODLLM_SAVE_STRATEGY = "no"
CODLLM_MULTICOD_SHUFFLE_LABELS = 1
CODLLM_MULTICOD_SYNTHETIC_TEXT_SEPARATORS = '[", ", " & ", " ", "; ", " / "]'


[sweep]
CODLLM_MULTICOD_SYNTHETIC_RATIO = [0, 0.1]
