#!/usr/bin/env bash
# ---------------- LSF directives ----------------
#BSUB -J codllm-train
#BSUB -q gpuh100
#BSUB -W 10:00
#BSUB -n 17
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=4GB]"
#BSUB -gpu "num=1:mode=exclusive_process"
#BSUB -env "all"
#BSUB -u s234854@dtu.dk
#BSUB -B
#BSUB -N
#BSUB -oo logs/%J.out
# -------------------------------------------------

set -euo pipefail

trap 'code=$?;
  printf "ERROR: jobs/train_h100_s234854.sh failed at line %s with exit code %s\n" "$LINENO" "$code";
  exit "$code"' ERR

PROJECT_DIR="${LSB_SUBCWD:-$(pwd)}"
cd "$PROJECT_DIR"
exec 2>&1

JOB_CONFIG_FILE="${JOB_CONFIG_FILE:-${1:-}}"
REQUIRE_JOB_CONFIG_FILE="${REQUIRE_JOB_CONFIG_FILE:-0}"
if [ "$REQUIRE_JOB_CONFIG_FILE" = "1" ] && [ -z "$JOB_CONFIG_FILE" ]; then
  echo "ERROR: REQUIRE_JOB_CONFIG_FILE=1 but JOB_CONFIG_FILE is not set."
  exit 1
fi
if [ -n "$JOB_CONFIG_FILE" ]; then
  if [ -f "$JOB_CONFIG_FILE" ]; then
    resolved_job_config="$JOB_CONFIG_FILE"
  elif [ -f "$PROJECT_DIR/$JOB_CONFIG_FILE" ]; then
    resolved_job_config="$PROJECT_DIR/$JOB_CONFIG_FILE"
  elif [ -f "$PROJECT_DIR/jobs/configs/$JOB_CONFIG_FILE" ]; then
    resolved_job_config="$PROJECT_DIR/jobs/configs/$JOB_CONFIG_FILE"
  else
    echo "ERROR: JOB_CONFIG_FILE '$JOB_CONFIG_FILE' does not exist."
    exit 1
  fi
  echo "Loading job config file: $resolved_job_config"
  set -a
  source "$resolved_job_config"
  set +a
else
  echo "INFO: JOB_CONFIG_FILE not provided; using defaults and inherited env vars."
fi

STORAGE_FOLDER="${STORAGE_FOLDER:-$HOME/codllm-storage}"
RUN_STORAGE_DIR="${RUN_STORAGE_DIR:-$STORAGE_FOLDER/codllm}"

HF_HOME="${HF_HOME:-$RUN_STORAGE_DIR/cache/huggingface}"
HF_HUB_CACHE="${HF_HUB_CACHE:-$HF_HOME/hub}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$RUN_STORAGE_DIR/cache/hf_datasets}"
TORCH_HOME="${TORCH_HOME:-$RUN_STORAGE_DIR/cache/torch}"
WANDB_DIR="${WANDB_DIR:-$RUN_STORAGE_DIR/cache/wandb}"
WANDB_CACHE_DIR="${WANDB_CACHE_DIR:-$WANDB_DIR/cache}"
XDG_CACHE_HOME_DIR="${XDG_CACHE_HOME_DIR:-$RUN_STORAGE_DIR/cache/xdg}"
UV_CACHE_DIR="${UV_CACHE_DIR:-$RUN_STORAGE_DIR/cache/uv}"
UV_PROJECT_ENVIRONMENT="${UV_PROJECT_ENVIRONMENT:-$RUN_STORAGE_DIR/.venv}"

TRAIN_OUTPUT_DIR="${TRAIN_OUTPUT_DIR:-$RUN_STORAGE_DIR/runs}"
TRAIN_DATA_RAW_DIR="${TRAIN_DATA_RAW_DIR:-$PROJECT_DIR/data/raw}"
TRAIN_DATA_PROCESSED_DIR="${TRAIN_DATA_PROCESSED_DIR:-$RUN_STORAGE_DIR/data/processed}"

CODLLM_OUTPUT_DIR="${CODLLM_OUTPUT_DIR:-$TRAIN_OUTPUT_DIR}"
CODLLM_DATA_RAW_DIR="${CODLLM_DATA_RAW_DIR:-$TRAIN_DATA_RAW_DIR}"
CODLLM_DATA_PROCESSED_DIR="${CODLLM_DATA_PROCESSED_DIR:-$TRAIN_DATA_PROCESSED_DIR}"

FORCE_REPROCESS="${FORCE_REPROCESS:-0}"
SYNC_ENV="${SYNC_ENV:-1}"
UV_SYNC_LOCK_FILE="${UV_SYNC_LOCK_FILE:-$RUN_STORAGE_DIR/.uv-sync.lock}"

CODLLM_SEED="${CODLLM_SEED:-42}"
CODLLM_HF_MODEL="${CODLLM_HF_MODEL:-google/flan-t5-small}"
CODLLM_TRUST_REMOTE_CODE="${CODLLM_TRUST_REMOTE_CODE:-0}"
CODLLM_LOAD_IN_8BIT="${CODLLM_LOAD_IN_8BIT:-0}"
CODLLM_USE_SAFETENSORS="${CODLLM_USE_SAFETENSORS:-0}"
CODLLM_DISABLE_SAFETENSORS_CONVERSION="${CODLLM_DISABLE_SAFETENSORS_CONVERSION:-1}"
CODLLM_VERBOSE="${CODLLM_VERBOSE:-1}"
CODLLM_TORCH_DTYPE="${CODLLM_TORCH_DTYPE:-auto}"
CODLLM_WANDB_LOG_MODEL="${CODLLM_WANDB_LOG_MODEL:-end}"
CODLLM_MAX_SOURCE_LENGTH="${CODLLM_MAX_SOURCE_LENGTH:-256}"
CODLLM_MAX_TARGET_LENGTH="${CODLLM_MAX_TARGET_LENGTH:-32}"
CODLLM_WARMUP_STEPS="${CODLLM_WARMUP_STEPS:-1000}"
CODLLM_NUM_TRAIN_EPOCHS="${CODLLM_NUM_TRAIN_EPOCHS:-4}"
CODLLM_PER_DEVICE_TRAIN_BATCH_SIZE="${CODLLM_PER_DEVICE_TRAIN_BATCH_SIZE:-8}"
CODLLM_PER_DEVICE_EVAL_BATCH_SIZE="${CODLLM_PER_DEVICE_EVAL_BATCH_SIZE:-8}"
CODLLM_GRADIENT_ACCUMULATION_STEPS="${CODLLM_GRADIENT_ACCUMULATION_STEPS:-2}"
CODLLM_DATALOADER_NUM_WORKERS="${CODLLM_DATALOADER_NUM_WORKERS:-4}"
CODLLM_LOGGING_STEPS="${CODLLM_LOGGING_STEPS:-25}"
CODLLM_EVAL_STEPS="${CODLLM_EVAL_STEPS:-200}"
CODLLM_SAVE_STEPS="${CODLLM_SAVE_STEPS:-5000}"
CODLLM_EVAL_STRATEGY="${CODLLM_EVAL_STRATEGY:-epoch}"
CODLLM_SAVE_STRATEGY="${CODLLM_SAVE_STRATEGY:-epoch}"
CODLLM_SAVE_STRATEGY_BEST_METRIC="${CODLLM_SAVE_STRATEGY_BEST_METRIC:-accuracy}"
CODLLM_LR="${CODLLM_LR:-3e-5}"
CODLLM_WEIGHT_DECAY="${CODLLM_WEIGHT_DECAY:-0.0}"
CODLLM_MAX_GRAD_NORM="${CODLLM_MAX_GRAD_NORM:-0.5}"
CODLLM_TRAINING_INPUT="${CODLLM_TRAINING_INPUT:-cod,age,sex}"
CODLLM_BALANCE_STRATEGY="${CODLLM_BALANCE_STRATEGY:-none}"
CODLLM_BALANCE_TARGET_QUANTILE="${CODLLM_BALANCE_TARGET_QUANTILE:-0.5}"
CODLLM_BALANCE_PERTURBATIONS_PER_SAMPLE="${CODLLM_BALANCE_PERTURBATIONS_PER_SAMPLE:-1}"
PYTHONHASHSEED="${PYTHONHASHSEED:-$CODLLM_SEED}"
CUBLAS_WORKSPACE_CONFIG="${CUBLAS_WORKSPACE_CONFIG:-:4096:8}"
OMP_NUM_THREADS="${OMP_NUM_THREADS:-${LSB_DJOB_NUMPROC:-1}}"
MKL_NUM_THREADS="${MKL_NUM_THREADS:-$OMP_NUM_THREADS}"
TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"

export HF_HOME HF_HUB_CACHE TRANSFORMERS_CACHE HF_DATASETS_CACHE TORCH_HOME
export WANDB_DIR WANDB_CACHE_DIR
export XDG_CACHE_HOME="$XDG_CACHE_HOME_DIR"
export UV_CACHE_DIR UV_PROJECT_ENVIRONMENT
export CODLLM_OUTPUT_DIR CODLLM_DATA_RAW_DIR CODLLM_DATA_PROCESSED_DIR
export CODLLM_SEED CODLLM_HF_MODEL CODLLM_TRUST_REMOTE_CODE
export CODLLM_LOAD_IN_8BIT CODLLM_USE_SAFETENSORS
export CODLLM_DISABLE_SAFETENSORS_CONVERSION
export CODLLM_VERBOSE CODLLM_TORCH_DTYPE
export CODLLM_WANDB_LOG_MODEL
export CODLLM_MAX_SOURCE_LENGTH CODLLM_MAX_TARGET_LENGTH
export CODLLM_WARMUP_STEPS CODLLM_NUM_TRAIN_EPOCHS
export CODLLM_PER_DEVICE_TRAIN_BATCH_SIZE CODLLM_PER_DEVICE_EVAL_BATCH_SIZE
export CODLLM_GRADIENT_ACCUMULATION_STEPS CODLLM_DATALOADER_NUM_WORKERS
export CODLLM_LOGGING_STEPS CODLLM_EVAL_STEPS CODLLM_SAVE_STEPS
export CODLLM_EVAL_STRATEGY CODLLM_SAVE_STRATEGY CODLLM_SAVE_STRATEGY_BEST_METRIC
export CODLLM_LR CODLLM_WEIGHT_DECAY CODLLM_MAX_GRAD_NORM
export CODLLM_TRAINING_INPUT
export CODLLM_BALANCE_STRATEGY CODLLM_BALANCE_TARGET_QUANTILE
export CODLLM_BALANCE_PERTURBATIONS_PER_SAMPLE
export PYTHONHASHSEED CUBLAS_WORKSPACE_CONFIG
export OMP_NUM_THREADS MKL_NUM_THREADS TOKENIZERS_PARALLELISM
export PYTHONUNBUFFERED=1

echo "Effective training environment:"
echo "  JOB_CONFIG_FILE=${resolved_job_config:-<none>}"
echo "  CODLLM_HF_MODEL=$CODLLM_HF_MODEL"
echo "  CODLLM_LR=$CODLLM_LR"
echo "  CODLLM_NUM_TRAIN_EPOCHS=$CODLLM_NUM_TRAIN_EPOCHS"
echo "  CODLLM_PER_DEVICE_TRAIN_BATCH_SIZE=$CODLLM_PER_DEVICE_TRAIN_BATCH_SIZE"
echo "  CODLLM_GRADIENT_ACCUMULATION_STEPS=$CODLLM_GRADIENT_ACCUMULATION_STEPS"
echo "  CODLLM_WEIGHT_DECAY=$CODLLM_WEIGHT_DECAY"
echo "  CODLLM_TRAINING_INPUT=$CODLLM_TRAINING_INPUT"
echo "  CODLLM_VERBOSE=$CODLLM_VERBOSE"

mkdir -p \
  "$RUN_STORAGE_DIR" \
  "$HF_HOME" \
  "$HF_HUB_CACHE" \
  "$TRANSFORMERS_CACHE" \
  "$HF_DATASETS_CACHE" \
  "$TORCH_HOME" \
  "$WANDB_DIR" \
  "$WANDB_CACHE_DIR" \
  "$XDG_CACHE_HOME_DIR" \
  "$UV_CACHE_DIR" \
  "$CODLLM_OUTPUT_DIR" \
  "$CODLLM_DATA_PROCESSED_DIR"

if [ ! -d "$CODLLM_DATA_RAW_DIR" ]; then
  echo "ERROR: CODLLM_DATA_RAW_DIR '$CODLLM_DATA_RAW_DIR' does not exist."
  exit 1
fi

if ! command -v uv >/dev/null 2>&1; then
  echo "ERROR: uv is not available in PATH."
  exit 1
fi

if command -v module >/dev/null 2>&1; then
  module load cuda/12.2
fi

if command -v nvidia-smi >/dev/null 2>&1; then
  nvidia-smi || true
fi

if [ "$SYNC_ENV" = "1" ]; then
  echo "Syncing Python environment with uv."
  if command -v flock >/dev/null 2>&1; then
    flock "$UV_SYNC_LOCK_FILE" uv sync --frozen --no-dev
  else
    echo "WARNING: flock is not available; running uv sync without cross-job locking."
    uv sync --frozen --no-dev
  fi
fi

train_cmd=(uv run python -m codllm.train)
if [ "$FORCE_REPROCESS" = "1" ]; then
  train_cmd+=(--force-reprocess)
fi

if [ -n "${TRAIN_EXTRA_ARGS:-}" ]; then
  read -r -a extra_args <<< "$TRAIN_EXTRA_ARGS"
  train_cmd+=("${extra_args[@]}")
fi

echo "Starting training on host with command: ${train_cmd[*]}"
"${train_cmd[@]}"

echo "Training finished successfully."
