base = "../base/h100-small.toml"
name = "base_small"
description = "simple run to check baseline model performance"
force_reprocess = false

[env]
CODLLM_DATASET_SIZE = 1.0
CODLLM_LR = 2.5e-5
CODLLM_NUM_TRAIN_EPOCHS = 128
CODLLM_SAVE_STRATEGY = "best"
CODLLM_MULTICOD_SHUFFLE_LABELS = 1
CODLLM_MULTICOD_SYNTHETIC_TEXT_SEPARATOR = ", "
CODLLM_MAX_LABEL_COUNT = 3
CODLLM_MULTICOD_SYNTHETIC_RATIO = 0.1
CODLLM_BALANCE_BASE_PERTURBATION_RATE = 0.5
CODLLM_BALANCE_PERTURBATION_MEAN = 0.05
CODLLM_BALANCE_PERTURBATION_VARIANCE = 0.02
